apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: otel-demo
  region: us-east-1

managedNodeGroups:
- name: ng-1
  instanceType: m5.large
  minSize: 2
  maxSize: 4
  desiredCapacity: 2
  privateNetworking: true

addons:
- name: vpc-cni
- name: coredns
- name: kube-proxy
