{
 "title": "Service Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate",
   "type": "gauge",
   "description": "Calculates error rate percentage for HTTP requests.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_duration_seconds_count{http_status_code=~\"\"}[5m])) * 100) / sum(rate(http_server_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "gauge",
   "description": "Monitors current number of active HTTP requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_active_requests) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "histogram",
   "description": "Shows 95th percentile of HTTP request durations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}